### PR TITLE
fix(local): use rawexec for hippo jobs

### PR DESCRIPTION
**Pull request by adamreese**
Fixes: #56

### CODE REVIEW

**Comment by lann** [comment]
..._now_ can we get rid of sudo?

**Comment by itowlson** [comment]
Works on WSL.  Haven't tested on Windows, Mac or "raw" Linux.

**Comment by bacongobbler** [comment]
We should be abundantly careful with this flag. I’m okay with this because it’s just for a demo repo, but because these jobs no longer run with any isolation systems in place, it is more likely a “host breakout” from the WASM runtime could incur more damage.

I’d like to figure out why the exec driver works on Linux and not on WSL, but given that we’re so close to the release date, we should just go ahead with this and investigate later.

**Review by bacongobbler — APPROVED** [review]
LGTM

**Pull request merged**
