### PR TITLE
add website documentation to docs/

### PR DESCRIPTION
**Pull request by vdice**
* Adds fermyon.dev website content to docs/
* Adds GH workflows for docs testing and dispatch/deploy

Ref https://github.com/fermyon/installer/issues/78

### CODE REVIEW

**Comment by bacongobbler** [comment]
The code here looks good to me. What's the best way to test this locally?

**Comment by vdice** [comment]
Thanks @bacongobbler.  To test the site locally: `cd docs && spin up`.  I've just pushed https://github.com/fermyon/installer/pull/79/commits/b300c8b98a30df14527b07760fffa9945f82e280 to update the dependency modules for the docs to versions that are compatible with the most recent [spin v0.4.0](https://github.com/fermyon/spin/releases/tag/v0.4.0) release.  So, it will be necessary that your local spin CLI be built from a recent commit from the `main` branch or directly from the aforementioned v0.4.0 release.

**Review by radu-matei — APPROVED** [review]
Manually tested locally, LGTM.
Thanks!

**Comment by vdice** [comment]
Thanks @radu-matei -- the most recent commit pins the `spin` version used in CI to the most recent release (v0.4.0) rather than canary.

**Pull request merged**
